import { Project } from "@/types";

export const projects: Project[] = [
    {
        title: 'Instafy',
        description: 'Social media app engineered for effortless connections, engaging content sharing, and smooth user experiences.',
        technologies: ['React', 'Typescript', 'Tailwind', 'Appwrite'],
        githubLink: 'https://github.com/ahmed45adel/Instafy',
        demoLink: 'https://instafy-eta.vercel.app',
        image: '/instafy.png',
      },
    {
        title: 'Sleep Tracker',
        description: 'Full-stack sleep tracking application with analytics and user authentication, built to help users monitor and analyze sleep patterns.',
        technologies: ['Next.js', 'React', 'Typescript', 'Tailwind', 'Prisma', 'Neon db', 'Clerk auth'],
        githubLink: 'https://github.com/ahmed45adel/sleep-tracker',
        demoLink: 'https://sleep-tracker-woad.vercel.app',
        image: '/sleeptracker.png',
      },
    {
        title: 'Chat App',
        description: 'A modern real-time chat application built with cutting-edge web technologies with real-time notifications and messages.',
        technologies: ['React', 'Typescript', 'Tailwind', 'Ably', 'Axios', 'Zustand'],
        githubLink: 'https://github.com/ahmed45adel/chat-app-frontend',
        demoLink: 'https://chat-app-frontend-three-theta.vercel.app',
        image: '/chatapp.png',
      },
    {
        title: 'Store with Admin Dashboard',
        description: 'E-commerce store designed for a seamless shopping experience with admin and customer roles.',
        technologies: ['React', 'Javascript', 'Tailwind', 'MongoDB', 'Redis', 'Stripe', 'Cloudinary', 'Express'],
        githubLink: 'https://github.com/ahmed45adel/store-frontend',
        demoLink: 'https://store-frontend-rose.vercel.app',
        image: '/commerce.png',
      },
    {
        title: 'Netflix Clone',
        description: 'A mern stack Netflix clone featuring trending content browsing, user authentication and responsive design.',
        technologies: ['React', 'Javascript', 'Tailwind', 'Axios', 'Zustand', 'MongoDB', 'Bcryptjs', 'Express'],
        githubLink: 'https://github.com/ahmed45adel/netflix-clone-frontend',
        demoLink: 'https://netflix-ahmed-frontend-omega.vercel.app',
        image: '/netflix.png',
      },
    {
        title: 'Colorlib Template',
        description: 'Responsive UI design inspired by Colorlib, offering customizable sections, clean typography and a beautiful design.',
        technologies: ['scss', 'css', 'html', 'Javascript'],
        githubLink: 'https://github.com/ahmed45adel/github.io.colorlib',
        demoLink: 'https://ahmed45adel.github.io/github.io.colorlib',
        image: '/colorlib.png',
      },
    {
        title: 'Zid Landing Page',
        description: 'Sleek and mobile friendly page showcasing services, features, and contact details with a fluid and fully responsive layout',
        technologies: ['Vue', 'css', 'html', 'Javascript'],
        githubLink: 'https://github.com/ahmed45adel/Ahmed-Adel-Inovola',
        demoLink: 'https://ahmed-adel-inovola.netlify.app',
        image: '/landing.png',
      },
    {
        title: 'Mogo Landing Page',
        description: 'Lightweight MoGo web theme showcasing modern design principles, mobile first responsiveness, and pre styled sections',
        technologies: ['css', 'html', 'Javascript'],
        githubLink: 'https://github.com/ahmed45adel/github.io-mogo',
        demoLink: 'https://ahmed45adel.github.io/github.io-mogo',
        image: '/mogo.png',
      },
    {
        title: 'My Reads',
        description: 'Single page application for managing and organizing books into custom shelves with interactive React UI.',
        technologies: ['React', 'Javascript'],
        githubLink: 'https://github.com/ahmed45adel/My-Reads',
        demoLink: 'https://ahmed-adel-myreads.netlify.app',
        image: '/myreads.png',
      },
  ];
